# https://www.home-assistant.io/integrations/binary_sensor.mqtt/
# https://www.home-assistant.io/integrations/device_tracker.mqtt
# https://www.home-assistant.io/integrations/sensor.mqtt/

mqtt:
  binary_sensor:
    - name: tesla_charge_port_door_open
      unique_id: tesla_charge_port_door_open
      state_topic: "teslamate/cars/1/charge_port_door_open"
      payload_on: "true"
      payload_off: "false"
      device_class: opening
      device:
        configuration_url: http://jlo-server:4000/
        manufacturer: Tesla
        model: Model 3
        name: Tesla Model 3 (Mémé)
        identifiers: jlo_tesla

    - name: tesla_doors_open
      unique_id: tesla_doors_open
      state_topic: "teslamate/cars/1/doors_open"
      payload_on: "true"
      payload_off: "false"
      device_class: opening
      device:
        identifiers: jlo_tesla

    - name: tesla_frunk_open
      unique_id: tesla_frunk_open
      state_topic: "teslamate/cars/1/frunk_open"
      payload_on: "true"
      payload_off: "false"
      device_class: opening
      device:
        identifiers: jlo_tesla

    - name: tesla_locked
      unique_id: tesla_locked
      state_topic: "teslamate/cars/1/locked"
      payload_on: "false"
      payload_off: "true"
      device_class: lock
      device:
        identifiers: jlo_tesla

    - name: tesla_plugged_in
      unique_id: tesla_plugged_in
      state_topic: "teslamate/cars/1/plugged_in"
      payload_on: "true"
      payload_off: "false"
      device_class: plug
      device:
        identifiers: jlo_tesla

    - name: tesla_sentry_mode
      unique_id: tesla_sentry_mode
      state_topic: "teslamate/cars/1/sentry_mode"
      payload_on: "true"
      payload_off: "false"
      device_class: running
      device:
        identifiers: jlo_tesla

    - name: tesla_trunk_open
      unique_id: tesla_trunk_open
      state_topic: "teslamate/cars/1/trunk_open"
      payload_on: "true"
      payload_off: "false"
      device_class: opening
      device:
        identifiers: jlo_tesla

    - name: tesla_windows_open
      unique_id: tesla_windows_open
      state_topic: "teslamate/cars/1/windows_open"
      payload_on: "true"
      payload_off: "false"
      device_class: opening
      device:
        identifiers: jlo_tesla

    - name: tesla_update_available
      unique_id: tesla_update_available
      state_topic: "teslamate/cars/1/update_available"
      payload_on: "true"
      payload_off: "false"
      entity_category: diagnostic
      device_class: update
      device:
        identifiers: jlo_tesla

  device_tracker:
    - name: tesla_device_tracker
      unique_id: tesla_device_tracker
      state_topic: "teslamate/cars/1/model"
      payload_reset: 3
      json_attributes_topic: "tesla/location"
      device:
        identifiers: jlo_tesla

  sensor:
    - name: tesla_battery_level
      unique_id: tesla_battery_level
      state_topic: "teslamate/cars/1/battery_level"
      unit_of_measurement: "%"
      device_class: battery
      device:
        identifiers: jlo_tesla

    - name: tesla_charger_power
      unique_id: tesla_charger_power
      state_topic: "teslamate/cars/1/charger_power"
      unit_of_measurement: kW
      device_class: power
      device:
        identifiers: jlo_tesla

    - name: tesla_latitude
      unique_id: tesla_latitude
      state_topic: "teslamate/cars/1/latitude"
      unit_of_measurement: °
      entity_category: diagnostic
      device:
        identifiers: jlo_tesla

    - name: tesla_longitude
      unique_id: tesla_longitude
      state_topic: "teslamate/cars/1/longitude"
      unit_of_measurement: °
      entity_category: diagnostic
      device:
        identifiers: jlo_tesla

    - name: tesla_rated_battery_range_km
      unique_id: tesla_rated_battery_range_km
      state_topic: "teslamate/cars/1/rated_battery_range_km"
      unit_of_measurement: km
      device_class: distance
      device:
        identifiers: jlo_tesla

    - name: tesla_state
      unique_id: tesla_state
      state_topic: "teslamate/cars/1/state"
      device_class: enum
      device:
        identifiers: jlo_tesla

    - name: tesla_time_to_full_charge
      unique_id: tesla_time_to_full_charge
      state_topic: "teslamate/cars/1/time_to_full_charge"
      unit_of_measurement: h
      device_class: duration
      device:
        identifiers: jlo_tesla

    - name: tesla_shift_state
      unique_id: tesla_shift_state
      state_topic: "teslamate/cars/1/shift_state"
      device_class: enum
      device:
        identifiers: jlo_tesla

    - name: tesla_inside_temp
      unique_id: tesla_inside_temp
      state_topic: "teslamate/cars/1/inside_temp"
      unit_of_measurement: "°C"
      device_class: temperature
      device:
        identifiers: jlo_tesla

    - name: tesla_charge_limit
      unique_id: tesla_charge_limit
      state_topic: "teslamate/cars/1/charge_limit_soc"
      unit_of_measurement: "%"
      device:
        identifiers: jlo_tesla

homeassistant:
  customize:
    device_tracker.tesla_device_tracker:
      entity_picture: "/local/tesla.jpg"
