# Default Config
default_config:

# Automations
automation: !include automations.yaml

# Scrits
script: !include scripts.yaml

# Scenes 
scene: !include scenes.yaml

# Packages
homeassistant:
  packages: !include_dir_named packages

frontend:
  themes: !include_dir_merge_named themes
