homeassistant:
  customize:
    media_player.jl_s_tv:
      unavailability_expected: true
    media_player.philips_android_tv:
      unavailability_expected: true
    media_player.tv_cast:
      unavailability_expected: true
    media_player.tv_plex:
      unavailability_expected: true
    remote.jl_s_tv:
      unavailability_expected: true
    update.m5stack_atom_echo_539640_firmware:
      unavailability_expected: true
