blueprint:
  name: Reduce volume of a media player when a voice assistant is listening.
  description: |
    Reduce the volume of a media player based on the state of a voice assistant
  domain: automation
  author: JLo
  input:
    assist_in_progress_binary_sensor:
      name: Assist in Progress
      description: Binary sensor representing the state of your voice assistant (most likely called `assist_in_progress`)
      selector:
        entity:
          filter:
            domain: "binary_sensor"
    media_player:
      name: Media player
      description: Media player where the volume will be reduced
      selector:
        entity:
          filter:
            domain: "media_player"
    threshold_volume:
      name: Threshold Volume
      description: Threshold volume to activate the automation. If the volume is below this value, nothing will happen. Test a few volume level to find the threshold where you cannot reliably activate your voice assistant anymore.
      selector:
        number:
          min: 0
          max: 1
          step: 0.1
          mode: slider
    listening_volume:
      name: Listening Volume
      description: Volume of the media player once the wake word will be detected and the voice assistant is listening to your command. (Must be lower than the Threshold Volume)
      selector:
        number:
          min: 0
          max: 1
          step: 0.1
          mode: slider

trigger:
  - platform: state
    entity_id:
      - !input assist_in_progress_binary_sensor
    to: "on"
condition:
  - condition: numeric_state
    entity_id: !input media_player
    attribute: volume_level
    above: !input threshold_volume
action:
  - variables:
      media_player_var: !input media_player
      listening_volume_var: !input listening_volume
  - variables:
      previous_volume_level: "{{state_attr(media_player_var,'volume_level')}}"
  - service: media_player.volume_set
    metadata: {}
    data:
      volume_level: !input listening_volume
    target:
      entity_id: !input media_player
  - wait_for_trigger:
      - platform: state
        entity_id:
          - !input assist_in_progress_binary_sensor
        to: "off"
        for:
          hours: 0
          minutes: 0
          seconds: 1
    timeout:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - if:
      - condition: template
        value_template: "{{state_attr(media_player_var,'volume_level')|float(0) == listening_volume_var|float(0)}}"
    then:
      - service: media_player.volume_set
        metadata: {}
        data:
          volume_level: "{{previous_volume_level}}"
        target:
          entity_id: !input media_player
mode: single
