esphome:
  name: respeakerv3
  friendly_name: ReSpeakerv3
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32s3

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
    version: recommended

logger:
api:
ota:
  safe_mode: false

psram:
  mode: octal
  speed: 80MHz

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  - source: github://synesthesiam/esphome-nabu
nabu:
  i2s_lrclk_pin: GPIO7
  i2s_bclk_pin: GPIO8
  i2s_mclk_pin: GPIO9
  i2s_din_pin: GPIO44
  i2s_dout_pin: GPIO043

microphone:
  - platform: nabu
    id: nabu_mic

speaker:
  - platform: nabu
    id: nabu_speaker

media_player:
  - platform: nabu
    id: nabu_media_player
    name: nabu_media_player
    internal: false
    speaker: nabu_speaker

micro_wake_word:
  model: okay_nabu
  on_wake_word_detected:
    - media_player.pause:
        id: nabu_media_player
    - voice_assistant.start:

voice_assistant:
  microphone: nabu_mic
  use_wake_word: false
  noise_suppression_level: 0
  auto_gain: 0dBFS
  volume_multiplier: 1
  speaker: nabu_speaker
  id: assist
  on_listening:
    - light.turn_on:
        id: led
        effect: "Fast Breathing Light"
  on_stt_vad_end:
    - light.turn_on:
        id: led
        effect: none
  on_tts_start:
    - light.turn_on:
        id: led
        effect: none
  on_end:
    - wait_until:
        not:
          speaker.is_playing:
    - micro_wake_word.start:
    - light.turn_off:
        id: led
    - media_player.play:
        id: nabu_media_player
  on_error:
    - light.turn_off:
        id: led
  on_client_connected:
  - micro_wake_word.start:
  on_client_disconnected:
    - micro_wake_word.stop:
    - voice_assistant.stop:

light:
  - platform: monochromatic
    id: led
    name: "Desk Lamp"
    output: light_output
    effects:
      - pulse:
          name: "Slow Breathing Light"
          transition_length: 5s  # 缓慢呼吸灯，渐变时间较长
      - pulse:
          name: "Fast Breathing Light"
          transition_length: 1s  # 快速呼吸灯，渐变时间较短

output:
  - platform: ledc
    id: light_output
    pin: GPIO21
    inverted: true
