substitutions:
  name: esp32-s3-box-3-5a9f28
  friendly_name: ESP32 S3 Box 3 5a9f28

  loading_illustration_file: box_illustrations/jarvis/loading.png
  idle_illustration_file: box_illustrations/jarvis/idle.png
  listening_illustration_file: box_illustrations/jarvis/listening.png
  thinking_illustration_file: box_illustrations/jarvis/thinking.png
  replying_illustration_file: box_illustrations/jarvis/replying.png
  error_illustration_file: box_illustrations/jarvis/error.png
  timer_finished_illustration_file: box_illustrations/jarvis/timer_finished.png

packages:
  esphome.voice-assistant:
    url: https://github.com/esphome/firmware
    file: wake-word-voice-assistant/esp32-s3-box-3.yaml
    refresh: 0s

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  
api:
  encryption:
    key: !secret voice-assistant-encryption-key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
