# https://www.home-assistant.io/integrations/systemmonitor/

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: processor_temperature
      - type: processor_use
      - type: throughput_network_in
        arg: end0
      - type: throughput_network_out
        arg: end0
